site_name: b3p
repo_url: https://github.com/wr1/b3p  # Add GitHub repository URL
repo_name: wr1/b3p  # Add repository name for display

theme:
  name: material
  palette:
    - scheme: slate  # Set dark mode as default

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
- Home: index.md
- Installation: installation.md
- Usage: 
  - Build: use/build.md
  - Input file: use/inputfile.md
  - FEA: use/fea.md
  - ANBA: use/anba.md
- Examples:
  - Blade Test: examples/blade_test.md
