site_name: b3p

theme:
  name: material
  features:
    - content.code.copy
    - navigation.sections
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
- Home: index.md
- Installation: installation.md
- Usage: 
  - Build: use/build.md
  - Input file: use/inputfile.md
  - FEA: use/fea.md
- Examples:
  - Blade Test: examples/blade_test.md
