name: Publish Python Package

on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - master
      - dev

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9.14

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Build package
      run: python -m build

    - name: Publish package
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: |
        python -m pip install twine
        twine upload dist/*

  # build-windows:
  #   runs-on: windows-latest

  #   steps:
  #   - uses: actions/checkout@v2

  #   - name: Set up Python
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: 3.9.13

  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       pip install build

  #   - name: Build package
  #     run: python -m build

  #   - name: Publish package
  #     env:
  #       TWINE_USERNAME: __token__
  #       TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
  #     run: |
  #       python -m pip install twine
  #       twine upload dist/*
