name: Run Tests

on:
  push:
    branches:
      - master  # Run tests on pushes to the main branch
      - dev
  pull_request:
    branches:
      - master  # Run tests on pull requests targeting the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12  # Specify your Python version

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
          ccblade_install 

      # Run tests
      - name: Run tests with pytest
        run: |
          poetry run pytest --cov=b3p
